# Changes here will be overwritten by Copier
_commit: v1.5.0
_src_path: https://github.com/growit-io/renovate-configuration
automerge_non_major: true
path_semantic_commit_type: ''
renovate_configuration_file: .renovaterc
use_semantic_prefix_fix_for_deps_chore_others_preset: true
