name: Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      - run: go test ./...
      # Run tests against the latest published Docker image.
      - uses: docker://ghcr.io/growit-io/terrahoot:latest
      # Build and test the Docker image on the current branch.
      - uses: ./
